export const mapNutrients = (n) => {
    n = {
        protein: n.protein,
        total_fat: n.totalFat,
        carbohydrates: n.carbs,
        calories: n.calories,
        total_sugars: n.totalSugars,
        dietary_fiber: n.dietaryFiber,
        sodium: n.sodium,
        added_sugars: n.addedSugars,
        cholesterol: n.cholesterol,
        trans_fat: n.transFat,
        saturated_fat: n.saturatedFat,
        calcium: n.calcium,
        iron: n.iron,
        magnesium: n.magnesium,
        potassium: n.potassium,
        zinc: n.zinc,
        chromium: n.chromium,
        copper: n.copper,
        iodine: n.iodine,
        manganese: n.manganese,
        molybdenum: n.molybdenum,
        selenium: n.selenium,
        vitamin_a: n.vitaminA,
        alpha_carotene: n.alphaCarotene,
        beta_carotene: n.betaCarotene,
        vitamin_e: n.vitaminE,
        vitamin_d: n.vitaminD,
        vitamin_c: n.vitaminC,
        thiamin_b1: n.thiaminB1,
        riboflavin_b2: n.riboflavinB2,
        niacin_b3: n.niacinB3,
        pantothenic_acid_b5: n.pantothenicAcidB5,
        pyridoxine_b6: n.pyridoxineB6,
        biotin_b7: n.biotinB7,
        folate_b9: n.folateB9,
        cyanocobalamin_b12: n.cyanocobalaminB12,
        choline: n.choline,
        vitamin_k2: n.vitaminK2,
        vitamin_k1: n.vitaminK1,
    };
    Object.keys(n).forEach((key) => n[key] === undefined && delete n[key]);
    return n;
};
