version: "3"
services:
  backend:
    tty: true
    container_name: "staplerecipes-backend"
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - DATABASE_URL=${DATABASE_URL}
  frontend:
    tty: true
    container_name: "staplerecipes-frontend"
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./fullchain.pem:/etc/nginx/certs/fullchain.pem
      - ./privkey.pem:/etc/nginx/certs/privkey.pem
