version: '3.8'
services:
  db:
    image: postgres:15-alpine
    tty: true
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - ./database/combined.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    restart: always
    tty: true
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - DATABASE_URL=db
    depends_on:
      - db
  frontend:
    restart: always
    tty: true
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '80:80'
volumes:
  pgdata:
