export const initialNutritionState = {
  protein: {
    nutrientId: 1003,
    nutrientName: 'Protein',
    dv: 50,
    amount: 0,
    unit: 'g',
  },
  totalFat: {
    nutrientId: 1004,
    nutrientName: 'Total Fat',
    dv: 78,
    amount: 0,
    unit: 'g',
  },
  carbs: {
    nutrientId: 1005,
    nutrientName: 'Total Carbohydrate',
    dv: 275,
    amount: 0,
    unit: 'g',
  },
  calories: {
    nutrientId: 1008,
    nutrientName: 'Calories',
    dv: null,
    amount: 0,
    unit: 'calories',
  },
  totalSugars: {
    nutrientId: 1063,
    nutrientName: 'Total Sugars',
    dv: null,
    amount: 0,
    unit: 'g',
  },
  dietaryFiber: {
    nutrientId: 1063,
    nutrientName: 'Dietary Fiber',
    dv: 28,
    amount: 0,
    unit: 'g',
  },
  sodium: {
    nutrientId: 1093,
    nutrientName: 'Sodium',
    dv: 2300,
    amount: 0,
    unit: 'mg',
  },
  addedSugars: {
    nutrientId: 1235,
    nutrientName: 'Added Sugars',
    dv: 50,
    amount: 0,
    unit: 'g',
  },
  cholesterol: {
    nutrientId: 1253,
    nutrientName: 'Cholesterol',
    dv: 300,
    amount: 0,
    unit: 'mg',
  },
  transFat: {
    nutrientId: 1257,
    nutrientName: 'Trans Fat',
    dv: null,
    amount: 0,
    unit: 'g',
  },
  saturatedFat: {
    nutrientId: 1258,
    nutrientName: 'Saturated Fat',
    dv: 20,
    amount: 0,
    unit: 'g',
  },
  calcium: {
    nutrientId: 1087,
    nutrientName: 'Calcium',
    dv: 1300,
    amount: 0,
    unit: 'mg',
  },
  iron: {
    nutrientId: 1089,
    nutrientName: 'Iron',
    dv: 18,
    amount: 0,
    unit: 'mg',
  },
  magnesium: {
    nutrientId: 1090,
    nutrientName: 'Magnesium',
    dv: 420,
    amount: 0,
    unit: 'mg',
  },
  potassium: {
    nutrientId: 1092,
    nutrientName: 'Potassium',
    dv: 4700,
    amount: 0,
    unit: 'mg',
  },
  zinc: {
    nutrientId: 1095,
    nutrientName: 'Zinc',
    dv: 11,
    amount: 0,
    unit: 'mg',
  },
  chromium: {
    nutrientId: 1096,
    nutrientName: 'Chromium',
    dv: 35,
    amount: 0,
    unit: 'mg',
  },
  copper: {
    nutrientId: 1098,
    nutrientName: 'Copper',
    dv: 0.9,
    amount: 0,
    unit: 'mg',
  },
  iodine: {
    nutrientId: 1100,
    nutrientName: 'Iodine',
    dv: 150,
    amount: 0,
    unit: 'mg',
  },
  manganese: {
    nutrientId: 1101,
    nutrientName: 'Manganese',
    dv: 2.3,
    amount: 0,
    unit: 'mg',
  },
  molybdenum: {
    nutrientId: 1102,
    nutrientName: 'Molybdenum',
    dv: 45,
    amount: 0,
    unit: 'mg',
  },
  selenium: {
    nutrientId: 1103,
    nutrientName: 'Selenium',
    dv: 55,
    amount: 0,
    unit: 'mg',
  },
  vitaminA: {
    nutrientId: 1106,
    nutrientName: 'Vitamin A',
    dv: 900,
    amount: 0,
    unit: 'mcg',
  },
  alphaCarotene: {
    nutrientId: 1107,
    nutrientName: 'Alpha Carotene',
    dv: null,
    amount: 0,
    unit: 'mcg',
  },
  betaCarotene: {
    nutrientId: 1108,
    nutrientName: 'Beta Carotene',
    dv: null,
    amount: 0,
    unit: 'mcg',
  },
  vitaminE: {
    nutrientId: 1109,
    nutrientName: 'Vitamin E',
    dv: 15,
    amount: 0,
    unit: 'mg',
  },
  vitaminD: {
    nutrientId: 1114,
    nutrientName: 'Vitamin D',
    dv: 20,
    amount: 0,
    unit: 'mcg',
  },
  vitaminC: {
    nutrientId: 1162,
    nutrientName: 'Vitamin C',
    dv: 90,
    amount: 0,
    unit: 'mg',
  },
  thiaminB1: {
    nutrientId: 1165,
    nutrientName: 'Thiamin (B1)',
    dv: 1.2,
    amount: 0,
    unit: 'mg',
  },
  riboflavinB2: {
    nutrientId: 1166,
    nutrientName: 'Riboflavin (B2)',
    dv: 1.3,
    amount: 0,
    unit: 'mg',
  },
  niacinB3: {
    nutrientId: 1167,
    nutrientName: 'Niacin (B3)',
    dv: 16,
    amount: 0,
    unit: 'mg',
  },
  pantothenicAcidB5: {
    nutrientId: 1170,
    nutrientName: 'Pantothenic Acid (B5)',
    dv: 5,
    amount: 0,
    unit: 'mg',
  },
  pyridoxineB6: {
    nutrientId: 1175,
    nutrientName: 'Pyridoxine (B6)',
    dv: 1.7,
    amount: 0,
    unit: 'mg',
  },
  biotinB7: {
    nutrientId: 1176,
    nutrientName: 'Biotin (B7)',
    dv: 30,
    amount: 0,
    unit: 'mcg',
  },
  folateB9: {
    nutrientId: 1177,
    nutrientName: 'Folate (B9)',
    dv: 400,
    amount: 0,
    unit: 'mcg',
  },
  cyanocobalaminB12: {
    nutrientId: 1178,
    nutrientName: 'Cyanocobalamin (B12)',
    dv: 2.4,
    amount: 0,
    unit: 'mcg',
  },
  choline: {
    nutrientId: 1180,
    nutrientName: 'Choline',
    dv: 550,
    amount: 0,
    unit: 'mg',
  },
  vitaminK2: {
    nutrientId: 1183,
    nutrientName: 'Vitamin K2',
    dv: 120,
    amount: 0,
    unit: 'mcg',
  },
  vitaminK1: {
    nutrientId: 1185,
    nutrientName: 'Vitamin K1',
    dv: 120,
    amount: 0,
    unit: 'mcg',
  },
} as NutritionState;
