import { fdcNutrients } from "../../data/mappings"

export const initialNutritionState = {
  protein: {
    nutrientId: 1003,
    ...fdcNutrients[1003],
    amount: 0,
    unit: 'g',
  },
  totalFat: {
    nutrientId: 1004,
    ...fdcNutrients[1004],
    amount: 0,
    unit: 'g',
  },
  carbs: {
    nutrientId: 1005,
    ...fdcNutrients[1005],
    amount: 0,
    unit: 'g',
  },
  totalSugars: {
    nutrientId: 1063,
    ...fdcNutrients[1063],
    amount: 0,
    unit: 'g',
  },
  dietaryFiber: {
    nutrientId: 1063,
    ...fdcNutrients[1063],
    amount: 0,
    unit: 'g',
  },
  sodium: {
    nutrientId: 1093,
    ...fdcNutrients[1093],
    amount: 0,
    unit: 'mg',
  },
  addedSugars: {
    nutrientId: 1235,
    ...fdcNutrients[1235],
    amount: 0,
    unit: 'g',
  },
  cholesterol: {
    nutrientId: 1253,
    ...fdcNutrients[1253],
    amount: 0,
    unit: 'mg',
  },
  transFat: {
    nutrientId: 1257,
    ...fdcNutrients[1257],
    amount: 0,
    unit: 'g',
  },
  saturatedFat: {
    nutrientId: 1258,
    ...fdcNutrients[1258],
    amount: 0,
    unit: 'g',
  },
  calcium: {
    nutrientId: 1087,
    ...fdcNutrients[1087],
    amount: 0,
    unit: 'mg',
  },
  iron: {
    nutrientId: 1089,
    ...fdcNutrients[1088],
    amount: 0,
    unit: 'mg',
  },
  magnesium: {
    nutrientId: 1090,
    ...fdcNutrients[1090],
    amount: 0,
    unit: 'mg',
  },
  potassium: {
    nutrientId: 1092,
    ...fdcNutrients[1092],
    amount: 0,
    unit: 'mg',
  },
  zinc: {
    nutrientId: 1095,
    ...fdcNutrients[1095],
    amount: 0,
    unit: 'mg',
  },
  chromium: {
    nutrientId: 1096,
    ...fdcNutrients[1096],
    amount: 0,
    unit: 'mg',
  },
  copper: {
    nutrientId: 1098,
    ...fdcNutrients[1098],
    amount: 0,
    unit: 'mg',
  },
  iodine: {
    nutrientId: 1100,
    ...fdcNutrients[1100],
    amount: 0,
    unit: 'mg',
  },
  manganese: {
    nutrientId: 1101,
    ...fdcNutrients[1101],
    amount: 0,
    unit: 'mg',
  },
  molybdenum: {
    nutrientId: 1102,
    ...fdcNutrients[1102],
    amount: 0,
    unit: 'mg',
  },
  selenium: {
    nutrientId: 1103,
    ...fdcNutrients[1103],
    amount: 0,
    unit: 'mg',
  },
  vitaminA: {
    nutrientId: 1106,
    ...fdcNutrients[1106],
    amount: 0,
    unit: 'ug',
  },
  alphaCarotene: {
    nutrientId: 1107,
    ...fdcNutrients[1107],    
    amount: 0,
    unit: 'ug',
  },
  betaCarotene: {
    nutrientId: 1108,
    ...fdcNutrients[1108],
    amount: 0,
    unit: 'ug',
  },
  vitaminE: {
    nutrientId: 1109,
    ...fdcNutrients[1109],
    amount: 0,
    unit: 'mg',
  },
  vitaminD: {
    nutrientId: 1114,
    ...fdcNutrients[1114],
    amount: 0,
    unit: 'ug',
  },
  vitaminC: {
    nutrientId: 1162,
    ...fdcNutrients[1162],
    amount: 0,
    unit: 'mg',
  },
  thiaminB1: {
    nutrientId: 1165,
    ...fdcNutrients[1165],
    amount: 0,
    unit: 'mg',
  },
  riboflavinB2: {
    nutrientId: 1166,
    ...fdcNutrients[1166],
    amount: 0,
    unit: 'mg',
  },
  niacinB3: {
    nutrientId: 1167,
    ...fdcNutrients[1167],
    amount: 0,
    unit: 'mg',
  },
  pantothenicAcidB5: {
    nutrientId: 1170,
    ...fdcNutrients[1170],
    amount: 0,
    unit: 'mg',
  },
  pyridoxineB6: {
    nutrientId: 1175,
    ...fdcNutrients[1175],
    amount: 0,
    unit: 'mg',
  },
  biotinB7: {
    nutrientId: 1176,
    ...fdcNutrients[1176],
    amount: 0,
    unit: 'ug',
  },
  folateB9: {
    nutrientId: 1177,
    ...fdcNutrients[1177],
    amount: 0,
    unit: 'ug',
  },
  cyanocobalaminB12: {
    nutrientId: 1178,
    ...fdcNutrients[1178],
    amount: 0,
    unit: 'ug',
  },
  choline: {
    nutrientId: 1180,
    ...fdcNutrients[1180],
    amount: 0,
    unit: 'mg',
  },
  vitaminK2: {
    nutrientId: 1183,
    ...fdcNutrients[1183],
    amount: 0,
    unit: 'ug',
  },
  vitaminK1: {
    nutrientId: 1185,
    ...fdcNutrients[1185],
    amount: 0,
    unit: 'ug',
  },
} as NutritionState;
